# Site settings
title: "Neal Lathia"
description: ""

author: Neal Lathia
email: neal.lathia@gmail.com
twitter_username: neal_lathia 
github_username: nlathia

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nlathia.github.io" # the base hostname & protocol for your site

google_analytics_id: 
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

